# Generated by Django 2.0 on 2018-01-19 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avscan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clamav', models.TextField()),
                ('bitdefender', models.TextField()),
                ('esetnod32', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.TextField()),
                ('libraries', models.TextField()),
                ('min_sdk', models.TextField()),
                ('providers', models.TextField()),
                ('receivers', models.TextField()),
                ('services', models.TextField()),
                ('target_sdk', models.TextField()),
                ('uses_permission', models.TextField()),
                ('version_code', models.TextField()),
                ('version_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('hash_md5', models.TextField()),
                ('hash_sha1', models.TextField()),
                ('hash_sha256', models.TextField()),
                ('hash_sha512', models.TextField()),
                ('time', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manifest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Project'),
        ),
        migrations.AddField(
            model_name='avscan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze.Project'),
        ),
    ]
